### ISSUE TITLE
firejailed-tor-browser.profile backporting

### ISSUE THREAD

**Issue by rusty-snake** [rusty-snake/firejailed-tor-browser#21]
# backporting status

Previous issue: #6

## 0.9.66 – <kbd>Ubuntu 22.04 LTS (Jammy Jellyfish)</kbd>

- [x] remove globals.local (60bbf4b)
- [x] `blacklist /tmp` (60bbf4b)
- [x] `read-only ${RUNUSER}` (60bbf4b)
- [ ] Revert '`read-only ${RUNUSER}` (60bbf4b)'
- [x] private-bin changes (d73d308)
- [x] minimized wusc (60bbf4b)
- [x] `hostname host` (60bbf4b)
- [x] `machine-id` (60bbf4b)
- [x] `blacklist /etc`, remove private-etc (60bbf4b)
- [ ] remove fake DISPLAY
- [ ] disable-proc.inc
- [ ] env GTK_THEME=Adwaita

## 0.9.64.4 – <kbd>Debian 11 (Bullseye)</kbd>

- [x] `read-only /tmp`+`read-only ${HOME}` (4142c3b6)
- [x] `read-only ${RUNUSER}` (f87593f)
- [ ] Revert '`read-only ${RUNUSER}` (f87593f)'
- [x] Block X11, Enable Wayland (4142c3b6)
- [x] remove globals.local (f87593f)
- [x] `blacklist /tmp` (f87593f)
- [x] private-bin changes (d73d308)
- [x] minimized wusc (f87593f)
- [x] `hostname host` (f87593f)
- [x] `machine-id` (f87593f)
- [x] `blacklist /etc`, remove private-etc (f87593f)
- [ ]  remove fake DISPLAY
- [ ] disable-proc.inc
- [ ] env GTK_THEME=Adwaita

## 0.9.62 – <kbd>Ubuntu 20.04 LTS (Focal Fossa)</kbd>

- [ ] disable-shell.inc
- [x] `blacklist /usr/libexec` (4142c3b6)
- [x] `read-only /tmp`+`read-only ${HOME}` (4142c3b6)
- [x] ~`read-only ${RUNUSER}`~
- [x] Block X11, Enable Wayland (4142c3b6)
- [ ] remove globals.local
- [ ] `blacklist /tmp`
- [x] private-bin changes (d73d308)
- [ ] minimized wusc
- [ ] `hostname host`
- [ ] `machine-id`
- [ ] `blacklist /etc`, remove private-etc
- [ ]  remove fake DISPLAY
- [ ] disable-proc.inc
- [ ] env GTK_THEME=Adwaita

## 0.9.58 – <kbd>Debian 10 (Buster)</kbd>

- [ ] `read-only /tmp`+`read-only ${HOME}`
- [x] ~`read-only ${RUNUSER}`~
- [ ] `blacklist /usr/libexec`
- [ ] disable-shell.inc
- [ ] seccomp changes
- [ ] Block X11, Enable Wayland
- [ ] remove kcmp from seccomp.drop
- [ ] remove globals.local
- [ ] `blacklist /tmp`
- [x] private-bin changes (d73d308)
- [ ] minimized wusc
- [ ] `hostname host`
- [ ] `machine-id`
- [ ] `blacklist /etc`, remove private-etc
- [ ] disable-proc.inc
- [ ] env GTK_THEME=Adwaita

**Comment by samsapti** [comment]
Hey @rusty-snake, is v0.9.68 on the list?

**Comment by rusty-snake** [comment]
`master/firejailed-tor-browser.profile` does not use any features available only in firejail>0.9.68 so no need to backport ATM.

---

0.9.52 – Ubuntu 18.04 LTS (Bionic Beaver): Will be removed when 22.04.1 is out.
0.9.66: ~Will be removed if Fedora Linux 36 it out and has 0.9.68.~ Used by Ubuntu 22.04 LTS (Jammy Jellyfish)
