### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by rusty-snake** [rusty-snake/firejailed-tor-browser#26]
Previous issues: #22, #24, #25.

Use GitHub Actions for testing.

Test:
 - [ ] ShellCheck install.sh, clean.sh, update.sh (#22).
 - [ ] Syntax check for firejailed-tor-browser.profile (#24).
       Using `firejail --profile=firejailed-tor-browser.profile --private-bin=true true` or similar.
 - [ ] Syntax check for firejailed-tor-browser.desktop (#24).
       Using `desktop-file-validate`.
 - [ ] Custom test for clean.sh, install.sh, updates.sh to see that they parse arguments correct, create/delete the right dirs/files, ...
